//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREETCL_ARC
    {
        public int OBJECTID { get; set; }
        public Nullable<int> FNODE_ { get; set; }
        public Nullable<int> TNODE_ { get; set; }
        public Nullable<int> LPOLY_ { get; set; }
        public Nullable<int> RPOLY_ { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<int> STREETCL_ { get; set; }
        public Nullable<int> STREETCL_ID { get; set; }
        public string PRE_DIR { get; set; }
        public string ST_NAME { get; set; }
        public string ST_TYPE { get; set; }
        public string SUF_DIR { get; set; }
        public Nullable<int> ZIP_LEFT { get; set; }
        public Nullable<int> ZIP_RIGHT { get; set; }
        public Nullable<int> L_F_ADD { get; set; }
        public Nullable<int> L_T_ADD { get; set; }
        public Nullable<int> R_F_ADD { get; set; }
        public Nullable<int> R_T_ADD { get; set; }
        public Nullable<int> ST_CODE { get; set; }
        public Nullable<int> L_HUNDRED { get; set; }
        public Nullable<int> R_HUNDRED { get; set; }
        public Nullable<int> SEG_ID { get; set; }
        public string ONEWAY { get; set; }
        public Nullable<short> CLASS { get; set; }
        public string RESPONSIBILITY { get; set; }
        public Nullable<System.DateTime> UPDATE_ { get; set; }
        public Nullable<System.DateTime> NEWSEGDATE { get; set; }
        public Nullable<short> MULTI_REP { get; set; }
        public string ADDSTCODE { get; set; }
        public string STNAME { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public string FacilityId { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> ConditionDate { get; set; }
        public Nullable<int> fnode { get; set; }
        public Nullable<int> tnode { get; set; }
    }
}
