//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class STREETCL_NODE
    {
        public int OBJECTID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public Nullable<int> ARC_ { get; set; }
        public Nullable<int> STREETCL_ { get; set; }
        public Nullable<int> STREETCL_ID { get; set; }
        public Nullable<int> NODE_ID { get; set; }
        public Nullable<int> INT_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_ { get; set; }
        public string INTERSECTION { get; set; }
        public string FacilityId { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> ConditionDate { get; set; }
    }
}
