//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public Nullable<short> CompanyTypeId { get; set; }
        public string Philadelphia_TaxId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Subdivision_Name { get; set; }
        public string RecCreateUserId { get; set; }
        public Nullable<System.DateTime> RecCreateDate { get; set; }
        public string RecEditUserId { get; set; }
        public Nullable<System.DateTime> RecEditDate { get; set; }
    }
}
