//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContact()
        {
            this.tblPermits = new HashSet<tblPermit>();
        }
    
        public int ContactId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public string Fax { get; set; }
        public string Pager { get; set; }
        public string Pager_PIN { get; set; }
        public string Cell_Phone { get; set; }
        public string EMailAddress { get; set; }
        public string Note { get; set; }
        public bool Active { get; set; }
        public string RecCreateUserId { get; set; }
        public Nullable<System.DateTime> RecCreateDate { get; set; }
        public string RecEditUserId { get; set; }
        public Nullable<System.DateTime> RecEditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermit> tblPermits { get; set; }
    }
}
