//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistrictType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDistrictType()
        {
            this.tblDistricts = new HashSet<tblDistrict>();
        }
    
        public short DistrictTypeID { get; set; }
        public string DistrictTypeName { get; set; }
        public string DistrictTypeAbbrev { get; set; }
        public string DT_Description { get; set; }
        public Nullable<int> boundary_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDistrict> tblDistricts { get; set; }
    }
}
