//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDistrict()
        {
            this.tblPermit_Districts = new HashSet<tblPermit_Districts>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
        public short Di_DistrictTypeID { get; set; }
        public string Di_ManagerName { get; set; }
        public string Di_ManagerTitle { get; set; }
        public string Di_Phone { get; set; }
        public string Di_Fax { get; set; }
        public string Di_Address { get; set; }
        public string Di_PostalCode { get; set; }
        public string Di_RegionId { get; set; }
        public Nullable<bool> Inactive { get; set; }
    
        public virtual tblDistrictType tblDistrictType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermit_Districts> tblPermit_Districts { get; set; }
    }
}
