//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNode
    {
        public Nullable<double> ARC_ { get; set; }
        public Nullable<int> STREETCL_ { get; set; }
        public Nullable<double> STREETCL_I { get; set; }
        public int NODE_ID { get; set; }
        public Nullable<double> INT_ID { get; set; }
        public Nullable<System.DateTime> UPDATE { get; set; }
        public string INTERSECTI { get; set; }
        public Nullable<double> X_COORD { get; set; }
        public Nullable<double> Y_COORD { get; set; }
    }
}
