//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermit_Fees
    {
        public short FeeTypeID { get; set; }
        public string FeeTypeName { get; set; }
        public string HighTrafficArea { get; set; }
        public Nullable<decimal> Minimum____ { get; set; }
        public string Minimum___s_ { get; set; }
        public string Minimum___t_ { get; set; }
        public Nullable<decimal> Rate____ { get; set; }
        public string Rate___s_ { get; set; }
        public string Rate___t_ { get; set; }
        public Nullable<decimal> Maximum____ { get; set; }
        public string Maximum___s_ { get; set; }
        public string Maximum___t_ { get; set; }
        public Nullable<decimal> Duration____ { get; set; }
        public Nullable<decimal> Duration____1 { get; set; }
        public string Duration__t_ { get; set; }
        public string Unit__s_ { get; set; }
        public string Unit__t_ { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
