//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermit_Extensions
    {
        public string Permit_Number { get; set; }
        public int Seq_Num { get; set; }
        public Nullable<System.DateTime> Init_ExpirationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Extend_Reason { get; set; }
        public string User_Id { get; set; }
        public Nullable<System.DateTime> RCDCHGDT { get; set; }
        public string RCDSTATUS { get; set; }
    
        public virtual tblPermit tblPermit { get; set; }
    }
}
