//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermit_Encroachment
    {
        public string Permit_Number { get; set; }
        public short Seq_Num { get; set; }
        public int EncroachmentTypeID { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string Description { get; set; }
    
        public virtual tblPermit tblPermit { get; set; }
    }
}
