//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermit_Locations
    {
        public string Permit_Number { get; set; }
        public short Seq_Num { get; set; }
        public Nullable<short> OccupancyTypeID { get; set; }
        public int OnSTCODE { get; set; }
        public Nullable<int> FromSTCODE { get; set; }
        public Nullable<int> ToSTCODE { get; set; }
        public string sOnActual { get; set; }
        public string sFromActual { get; set; }
        public string sToActual { get; set; }
        public string sHighTrafficArea { get; set; }
        public Nullable<int> ReferenceTypeID { get; set; }
        public string ReferenceValue { get; set; }
        public string LocationType { get; set; }
    
        public virtual tblPermit tblPermit { get; set; }
    }
}
