//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStreet
    {
        public Nullable<int> FNODE_ { get; set; }
        public Nullable<int> TNODE_ { get; set; }
        public Nullable<double> LPOLY_ { get; set; }
        public Nullable<double> RPOLY_ { get; set; }
        public Nullable<double> LENGTH { get; set; }
        public Nullable<double> STCL2_ { get; set; }
        public Nullable<double> STCL2_ID { get; set; }
        public string PRE_DIR { get; set; }
        public string ST_NAME { get; set; }
        public string ST_TYPE { get; set; }
        public string SUF_DIR { get; set; }
        public Nullable<double> ZIP_LEFT { get; set; }
        public Nullable<double> ZIP_RIGHT { get; set; }
        public Nullable<double> L_F_ADD { get; set; }
        public Nullable<double> L_T_ADD { get; set; }
        public Nullable<double> R_F_ADD { get; set; }
        public Nullable<double> R_T_ADD { get; set; }
        public Nullable<int> ST_CODE { get; set; }
        public Nullable<double> L_HUNDRED { get; set; }
        public Nullable<double> R_HUNDRED { get; set; }
        public int SEG_ID { get; set; }
        public string ONEWAY { get; set; }
        public Nullable<double> CLASS { get; set; }
        public string RESPONSIBL { get; set; }
        public Nullable<System.DateTime> UPDATE { get; set; }
        public Nullable<System.DateTime> NEWSEGDATE { get; set; }
        public Nullable<double> MULTI_REP { get; set; }
        public string STNAME { get; set; }
        public string StreetName { get; set; }
        public string StreetNameShort { get; set; }
    }
}
