//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phila.Data.EntityModels.Streets
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpecialNode
    {
        public int NODE_ID { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> Primary_StCode { get; set; }
        public string Primary_ST_Name { get; set; }
        public Nullable<int> Secondary_StCode { get; set; }
        public string Secondary_ST_Name { get; set; }
    }
}
