// <auto-generated />
namespace Phila.Web.Api.Streets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aspnetdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aspnetdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201511081941101_aspnetdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
